- list: unauthorized_applications
  items: [
    '"v2ray"'
  ]

- list: process
  items: [
    "proc.cmdline"
    "proc.name"
  ] 

- macro: unauthorized_processes
  condition: process in (unauthorized_applications)


- rule: Unauthorized application is running
  desc: Detect that an unauthorized application is running
  condition: unauthorized_processes and (evt.type = execve)
  output: An unauthorized application is running (command=%proc.cmdline port=%fd.rport ip=%fd.rip container=%container.info image=%container.image.repository k8s.ns.name)
  priority: CRITICAL
  tags: [proxy, okteto_cloud, crytoconcurrency, mining]