- list: unauthorized_applications
  items: [
    '"v2ray"'
  ]

- macro: unauthorized_processes_name
  condition: proc.name in (unauthorized_applications)


- macro: unauthorized_processes_pname
  condition: proc.pname in (unauthorized_applications)

- rule: Unauthorized application is running
  desc: Detect that an unauthorized application is running
  condition: (unauthorized_processes_name or unauthorized_processes_pname) and (evt.type = execve)
  output: An unauthorized application is running (command=%proc.cmdline port=%fd.rport ip=%fd.rip container2=%container.id container=%container.info image=%container.image.repository test=k8s.info)
  priority: CRITICAL
  tags: [proxy, okteto_cloud, crytoconcurrency, mining]