- list: unauthorized_applications
  items: [
    '"v2ray"'
  ]

- macro: unauthorized_processes
  condition: proc.name in (unauthorized_applications)

- rule: Unauthorized application is running
  desc: Detect that an unauthorized application is running
  condition: container.id != host and unauthorized_processes
  output: An unauthorized application is running (command=%proc.cmdline port=%fd.rport ip=%fd.rip container=%container.info image=%container.image.repository)
  priority: CRITICAL
  tags: [proxy, okteto_cloud, crytoconcurrency, mining]
