- list: unauthorized_applications
  items: [
    '"v2ray"'
  ]

- macro: container
  condition: container.id != host

- macro: unauthorized_processes_name
  condition: proc.name in (unauthorized_applications)


- macro: unauthorized_processes_pname
  condition: proc.pname in (unauthorized_applications)

- rule: Unauthorized application is running
  desc: Detect that an unauthorized application is running
  condition: container and (unauthorized_processes_name or unauthorized_processes_pname) and (evt.type = execve)
  output: An unauthorized application is running (command=%proc.cmdline  container2=%container.name container=%container.info image=%container.image.repository)
  priority: CRITICAL
  tags: [proxy, okteto_cloud, crytoconcurrency, mining]
